[build]
  command = "bash ./build.sh"
  publish = ".next"
  node_compat = true

[build.environment]
  NODE_VERSION = "18"
  NODE_OPTIONS = "--no-warnings --max-old-space-size=4096"
  NEXT_TELEMETRY_DISABLED = "1"