[build]
  command = "npm run build"
  publish = "out"  # export modunu kullandığımız için build çıktısı "out" klasöründe olacak
  node_compat = true

[build.environment]
  NODE_VERSION = "18"
  NODE_OPTIONS = "--no-warnings --max-old-space-size=4096"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_MINIMIZE = "true"